name: CI/CD - Docker Build and Publish

on:

  push:
    branches: [ "master" ] 
  workflow_dispatch:

permissions:
  contents: read 

env:
  DOCKER_IMAGE: 'esanatyoe/proyecto1' 

jobs:
  build-and-publish-docker:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read 
      packages: write 

    steps:
      - name: 1. Checkout del código
        uses: actions/checkout@v4

      - name: 2. Modificar el título de la página
        run: |
          TITLE_FILE="src/main/resources/templates/index.html" 
          NEW_TITLE="Gestión de usuarios: Natalia Alejo Pérez - Commit: ${{ github.sha }}"
          
          if [ -f "$TITLE_FILE" ]; then
            sed -i 's|<title>.*</title>|<title>'"$NEW_TITLE"'</title>|g' "$TITLE_FILE"
            echo "Título de la página cambiado en $TITLE_FILE."
          else
            echo "Advertencia: No se encontró el archivo del título en $TITLE_FILE. Continuando sin modificar."
          fi
          

      - name: 3. Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.SESIONDOCKER }}
          password: ${{ secrets.SESIONTOKEN }}

      - name: 4. Definir Tags (latest y SHA)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=sha,format=short 
            type=raw,value=latest
            
      - name: 5. Construir y Publicar la imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: . 
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: 6. Documentar los cambios y Comando de Desplie
        run: |
          echo "--- DOCUMENTACIÓN FINAL ---"
          echo "La imagen se publicó con éxito en Docker Hub con el hash: ${{ github.sha }}"
          echo "Comando para despliegue:"
          echo "docker run -d -p 8080:8080 ${{ env.DOCKER_IMAGE }}:latest"
